/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "secondary-fixed-dim": "#ccd7d2",
                "on-error-container": "#ffd2c8",
                "surface-container-lowest": "#000000",
                "error-container": "#b92902",
                "surface-dim": "#0a0f0d",
                "on-background": "#f9fdf9",
                "on-error": "#450900",
                "on-surface": "#f9fdf9",
                "secondary-container": "#3e4945",
                "surface-container-high": "#1a211e",
                "primary-dim": "#2be800",
                "on-tertiary-fixed-variant": "#005e63",
                "surface-container": "#151b18",
                "background": "#0a0f0d",
                "outline-variant": "#719181",
                "primary-container": "#2ff801",
                "tertiary-fixed-dim": "#00deea",
                "on-tertiary-fixed": "#003f43",
                "tertiary-container": "#17eefa",
                "secondary-dim": "#e0f2eb",
                "outline": "#a4ccba",
                "surface-variant": "#202724",
                "on-surface-variant": "#f0fcf6",
                "secondary-fixed": "#f0fdf6",
                "primary-fixed-dim": "#2be800",
                "error-dim": "#d53d18",
                "on-secondary-fixed": "#a6c7b8",
                "on-secondary": "#c5ebd8",
                "on-primary-container": "#0b5800",
                "on-tertiary": "#005d62",
                "on-primary-fixed-variant": "#0d6200",
                "on-tertiary-container": "#005458",
                "surface-container-low": "#0f1512",
                "surface": "#0a0f0d",
                "on-primary-fixed": "#064200",
                "error": "#ff7351",
                "primary-fixed": "#2ff801",
                "surface-tint": "#8eff71",
                "primary": "#8eff71",
                "tertiary": "#88f6ff",
                "tertiary-fixed": "#17eefa",
                "secondary": "#dae5e0",
                "inverse-primary": "#106f00",
                "tertiary-dim": "#00deea",
                "surface-bright": "#262e2a",
                "inverse-surface": "#f6faf6",
                "on-secondary-container": "#c8d3ce",
                "on-secondary-fixed-variant": "#535e5a",
                "inverse-on-surface": "#515653",
                "surface-container-highest": "#202724",
                "on-primary": "#0d6100"
            },
            fontFamily: {
                "headline": ["Inter"],
                "body": ["Space Grotesk"],
                "label": ["Space Grotesk"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
    plugins: [],
}
